spring:
  application:
    name: account-service

server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: INFO
    com.bankapp.accountservice: INFO
